title: The Orbital Space Ontology & Terminology/Taxonomy Project
description: Knowledge Modeling for Space
by Robert J. Rovetto
creator: 
name: Robert J. Rovetto
url: https://scholar.google.com/citations?user=jTkGEiMAAAAJ&hl=en&oi=sra
google_analytics: 
show_downloads: false
theme: jekyll-theme-slate

gems:
  - jekyll-mentions
